# Cloudflare Pages Configuration for ब्लैक जॉर्ज
# This file is for Wrangler CLI - Pages dashboard will use its own build settings

name = "george-console"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

# For Cloudflare Pages, remove this line - it will be configured in dashboard
# pages_build_output_dir = ".vercel/output/static"

# Custom domains will be configured via CLI after deployment